insert into petshop (name, kind, age) values ('Tarrah', 'Blue fox', 1);
insert into petshop (name, kind, age) values ('Korie', 'Cliffchat, mocking', 19);
insert into petshop (name, kind, age) values ('Sybille', 'African black crake', 18);
insert into petshop (name, kind, age) values ('Hilda', 'Wallaby, bennett''s', 9);
insert into petshop (name, kind, age) values ('Parke', 'Black-winged stilt', 10);
insert into petshop (name, kind, age) values ('Alis', 'Barbet, levaillant''s', 14);
insert into petshop (name, kind, age) values ('Jerrie', 'Catfish, blue', 18);
insert into petshop (name, kind, age) values ('Anet', 'Screamer, southern', 7);
insert into petshop (name, kind, age) values ('Cirstoforo', 'Eurasian beaver', 3);
insert into petshop (name, kind, age) values ('Vail', 'Ovenbird', 3);
insert into petshop (name, kind, age) values ('Winnah', 'Sockeye salmon', 13);
insert into petshop (name, kind, age) values ('Chicky', 'Egyptian vulture', 16);
insert into petshop (name, kind, age) values ('Worden', 'Chipmunk, least', 20);
insert into petshop (name, kind, age) values ('Jeniffer', 'Stork, black-necked', 13);
insert into petshop (name, kind, age) values ('Vidovik', 'Crane, wattled', 7);
insert into petshop (name, kind, age) values ('Obediah', 'Frogmouth, tawny', 20);
insert into petshop (name, kind, age) values ('Hillyer', 'Eagle, tawny', 3);
insert into petshop (name, kind, age) values ('Marcelline', 'Bengal vulture', 8);
insert into petshop (name, kind, age) values ('Trudy', 'Mongoose, yellow', 18);
insert into petshop (name, kind, age) values ('Nixie', 'Bee-eater, nubian', 20);
insert into petshop (name, kind, age) values ('Dave', 'Sifaka, verreaux''s', 18);
insert into petshop (name, kind, age) values ('Bartolomeo', 'Ibex', 17);
insert into petshop (name, kind, age) values ('Lew', 'Water monitor', 12);
insert into petshop (name, kind, age) values ('Zechariah', 'Groundhog', 18);
insert into petshop (name, kind, age) values ('Arie', 'Jacana, african', 1);
insert into petshop (name, kind, age) values ('Sheffie', 'Painted stork', 4);
insert into petshop (name, kind, age) values ('Anna-diane', 'Polecat, african', 9);
insert into petshop (name, kind, age) values ('Carlina', 'Four-horned antelope', 12);
insert into petshop (name, kind, age) values ('Chariot', 'Elk, Wapiti', 16);
insert into petshop (name, kind, age) values ('Briggs', 'Marten, american', 1);
insert into petshop (name, kind, age) values ('Ferdinanda', 'Black and white colobus', 4);
insert into petshop (name, kind, age) values ('Sybilla', 'Black-fronted bulbul', 4);
insert into petshop (name, kind, age) values ('Hildagarde', 'Galapagos sea lion', 14);
insert into petshop (name, kind, age) values ('Bridie', 'Pied avocet', 9);
insert into petshop (name, kind, age) values ('Pierrette', 'Common mynah', 16);
insert into petshop (name, kind, age) values ('Nels', 'Kookaburra, laughing', 20);
insert into petshop (name, kind, age) values ('Saraann', 'Little heron', 5);
insert into petshop (name, kind, age) values ('Lil', 'Ring-tailed lemur', 8);
insert into petshop (name, kind, age) values ('Eileen', 'Asian lion', 1);
insert into petshop (name, kind, age) values ('Aridatha', 'Egret, snowy', 19);
insert into petshop (name, kind, age) values ('Sula', 'Jackal, golden', 5);
insert into petshop (name, kind, age) values ('Standford', 'Grey-footed squirrel', 12);
insert into petshop (name, kind, age) values ('Clarie', 'Otter, african clawless', 1);
insert into petshop (name, kind, age) values ('Cece', 'Alligator, mississippi', 15);
insert into petshop (name, kind, age) values ('Andee', 'Rattlesnake, horned', 12);
insert into petshop (name, kind, age) values ('Elsey', 'Squirrel, palm', 1);
insert into petshop (name, kind, age) values ('Carree', 'Steenbuck', 3);
insert into petshop (name, kind, age) values ('Sigismundo', 'Cormorant, large', 18);
insert into petshop (name, kind, age) values ('Yard', 'Lourie, grey', 13);
insert into petshop (name, kind, age) values ('Joel', 'Wildebeest, blue', 6);
insert into petshop (name, kind, age) values ('Brandice', 'Red meerkat', 13);
insert into petshop (name, kind, age) values ('Rhianna', 'Galapagos penguin', 2);
insert into petshop (name, kind, age) values ('Grant', 'Eastern cottontail rabbit', 11);
insert into petshop (name, kind, age) values ('Caldwell', 'Springhare', 9);
insert into petshop (name, kind, age) values ('Gwenny', 'Desert tortoise', 20);
insert into petshop (name, kind, age) values ('Hale', 'Dove, emerald-spotted wood', 14);
insert into petshop (name, kind, age) values ('Grantley', 'Cormorant, pied', 6);
insert into petshop (name, kind, age) values ('Quincey', 'Striped hyena', 6);
insert into petshop (name, kind, age) values ('Shae', 'Beaver, eurasian', 8);
insert into petshop (name, kind, age) values ('Georgy', 'Rufous tree pie', 15);
insert into petshop (name, kind, age) values ('Lyndell', 'African polecat', 18);
insert into petshop (name, kind, age) values ('Flore', 'Whale, southern right', 6);
insert into petshop (name, kind, age) values ('Ellette', 'European shelduck', 11);
insert into petshop (name, kind, age) values ('Luce', 'Black spider monkey', 4);
insert into petshop (name, kind, age) values ('Libbey', 'Porcupine, crested', 8);
insert into petshop (name, kind, age) values ('Sheridan', 'Greater flamingo', 16);
insert into petshop (name, kind, age) values ('Leonerd', 'Old world fruit bat (unidentified)', 19);
insert into petshop (name, kind, age) values ('Pryce', 'Violet-eared waxbill', 5);
insert into petshop (name, kind, age) values ('Fonz', 'Bear, black', 5);
insert into petshop (name, kind, age) values ('Nanine', 'Western spotted skunk', 12);
insert into petshop (name, kind, age) values ('Maressa', 'Glossy starling (unidentified)', 14);
insert into petshop (name, kind, age) values ('Rena', 'Egyptian goose', 5);
insert into petshop (name, kind, age) values ('Luciano', 'Tokay gecko', 4);
insert into petshop (name, kind, age) values ('Gretal', 'Brazilian otter', 9);
insert into petshop (name, kind, age) values ('Leslie', 'Gonolek, burchell''s', 14);
insert into petshop (name, kind, age) values ('Murry', 'Bennett''s wallaby', 5);
insert into petshop (name, kind, age) values ('Nolana', 'Spoonbill, european', 14);
insert into petshop (name, kind, age) values ('Westbrook', 'Bustard, stanley', 4);
insert into petshop (name, kind, age) values ('Jodie', 'Red lava crab', 1);
insert into petshop (name, kind, age) values ('Christy', 'Woodrat (unidentified)', 5);
insert into petshop (name, kind, age) values ('Sarette', 'Desert tortoise', 13);
insert into petshop (name, kind, age) values ('Bastian', 'Fox, crab-eating', 14);
insert into petshop (name, kind, age) values ('Roshelle', 'Heron, goliath', 14);
insert into petshop (name, kind, age) values ('Lavina', 'Legaan, Monitor (unidentified)', 15);
insert into petshop (name, kind, age) values ('Mame', 'Baboon, savanna', 11);
insert into petshop (name, kind, age) values ('Josephina', 'Gila monster', 10);
insert into petshop (name, kind, age) values ('Emmett', 'Glider, sugar', 1);
insert into petshop (name, kind, age) values ('Claudette', 'Partridge, coqui', 5);
insert into petshop (name, kind, age) values ('Junette', 'Australian brush turkey', 5);
insert into petshop (name, kind, age) values ('Joyan', 'Sloth, hoffman''s', 10);
insert into petshop (name, kind, age) values ('Kenton', 'Denham''s bustard', 11);
insert into petshop (name, kind, age) values ('Bill', 'Dove, ring', 4);
insert into petshop (name, kind, age) values ('Elisabetta', 'Monster, gila', 15);
insert into petshop (name, kind, age) values ('Merralee', 'Black-capped chickadee', 2);
insert into petshop (name, kind, age) values ('Constantino', 'Prehensile-tailed porcupine', 7);
insert into petshop (name, kind, age) values ('Giffer', 'Hartebeest, coke''s', 3);
insert into petshop (name, kind, age) values ('Liane', 'Grouse, sage', 1);
insert into petshop (name, kind, age) values ('Edmon', 'Chimpanzee', 2);
insert into petshop (name, kind, age) values ('Bobby', 'Fox, silver-backed', 10);
insert into petshop (name, kind, age) values ('Flora', 'Indian red admiral', 15);